<?php

/**
 * @file
 * NRCS Core module hooks.
 */

/**
 * Implements hook_theme().
 */
function nrcs_core_theme($existing, $type, $theme, $path) {
  return \Drupal::service('nrcs_core.theme_helper')
    ->hookTheme($existing, $type, $theme, $path);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nrcs_core_preprocess_block(&$variables) {
  \Drupal::service('nrcs_core.theme_helper')
    ->hookPreprocessBlock($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nrcs_core_preprocess_block__system_branding_block(&$variables) {
  \Drupal::service('nrcs_core.theme_helper')
    ->hookPreprocessSystemBrandingBlock($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nrcs_core_preprocess_region__footer_secondary(&$variables) {
  \Drupal::service('nrcs_core.theme_helper')
    ->hookPreprocessRegionFooterSecondary($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nrcs_core_preprocess_paragraph__nrcs_call_to_action(&$variables) {
  \Drupal::service('nrcs_core.theme_helper')
    ->hookPreprocessParagraphCallToAction($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nrcs_core_preprocess_paragraph__nrcs_call_to_action__nrcs_hero_callout_view(&$variables) {
  \Drupal::service('nrcs_core.theme_helper')
    ->hookPreprocessParagraphCallToAction($variables);
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function nrcs_core_theme_suggestions_menu_alter(
  &$suggestions,
  array $variables
) {
  \Drupal::service('nrcs_core.theme_helper')
    ->hookThemeSuggestionsMenuAlter($suggestions, $variables);
}
